/* Headers/Additions/GNUstepBase/config.h.  Generated by configure.  */
/* Headers/Additions/GNUstepBase/config.h.in.  Generated from configure.ac by autoheader.  */

/* Define if SO_REUSEADDR is broken on this system */
/* #undef BROKEN_SO_REUSEADDR */

/* Define if your system terminates the final argument in /proc/$$/cmdline */
#define CMDLINE_TERMINATED 1

/* Define if constructors are automatically loaded */
#define CON_AUTOLOAD 1

/* Built in default value for GNUstep config file */
#define GNUSTEP_TARGET_CONFIG_FILE "/etc/GNUstep/GNUstep.conf"

/* Built in default value for GNUstep local apps */
#define GNUSTEP_TARGET_LOCAL_ADMIN_APPS "/usr/GNUstep/Local/Applications/Admin"

/* Built in default value for GNUstep local tools */
#define GNUSTEP_TARGET_LOCAL_ADMIN_TOOLS "/usr/GNUstep/Local/Tools/Admin"

/* Built in default value for GNUstep local apps */
#define GNUSTEP_TARGET_LOCAL_APPS "/usr/GNUstep/Local/Applications"

/* Built in default value for GNUstep local documentation */
#define GNUSTEP_TARGET_LOCAL_DOC "/usr/GNUstep/Local/Library/Documentation"

/* Built in default value for GNUstep local info documentation */
#define GNUSTEP_TARGET_LOCAL_DOC_INFO "/usr/GNUstep/Local/Library/Documentation/info"

/* Built in default value for GNUstep local manpages documentation */
#define GNUSTEP_TARGET_LOCAL_DOC_MAN "/usr/GNUstep/Local/Library/Documentation/man"

/* Built in default value for GNUstep local headers */
#define GNUSTEP_TARGET_LOCAL_HEADERS "/usr/GNUstep/Local/Library/Headers"

/* Built in default value for GNUstep local libraries */
#define GNUSTEP_TARGET_LOCAL_LIBRARIES "/usr/GNUstep/Local/Library/Libraries"

/* Built in default value for GNUstep local library */
#define GNUSTEP_TARGET_LOCAL_LIBRARY "/usr/GNUstep/Local/Library"

/* Built in default value for GNUstep local tools */
#define GNUSTEP_TARGET_LOCAL_TOOLS "/usr/GNUstep/Local/Tools"

/* Built in default value for GNUstep Local Users directory */
#define GNUSTEP_TARGET_LOCAL_USERS_DIR ""

/* Built in default value for GNUstep local web apps */
#define GNUSTEP_TARGET_LOCAL_WEB_APPS "/usr/GNUstep/Local/Library/WebApplications"

/* Built in default value for GNUstep Makefiles */
#define GNUSTEP_TARGET_MAKEFILES "/usr/GNUstep/System/Library/Makefiles"

/* Built in default value for GNUstep network apps */
#define GNUSTEP_TARGET_NETWORK_ADMIN_APPS "/usr/GNUstep/Local/Applications/Admin"

/* Built in default value for GNUstep system tools */
#define GNUSTEP_TARGET_NETWORK_ADMIN_TOOLS "/usr/GNUstep/Local/Tools/Admin"

/* Built in default value for GNUstep network apps */
#define GNUSTEP_TARGET_NETWORK_APPS "/usr/GNUstep/Local/Applications"

/* Built in default value for GNUstep network documentation */
#define GNUSTEP_TARGET_NETWORK_DOC "/usr/GNUstep/Local/Library/Documentation"

/* Built in default value for GNUstep network info documentation */
#define GNUSTEP_TARGET_NETWORK_DOC_INFO "/usr/GNUstep/Local/Library/Documentation/info"

/* Built in default value for GNUstep network manpages documentation */
#define GNUSTEP_TARGET_NETWORK_DOC_MAN "/usr/GNUstep/Local/Library/Documentation/man"

/* Built in default value for GNUstep network headers */
#define GNUSTEP_TARGET_NETWORK_HEADERS "/usr/GNUstep/Local/Library/Headers"

/* Built in default value for GNUstep network libraries */
#define GNUSTEP_TARGET_NETWORK_LIBRARIES "/usr/GNUstep/Local/Library/Libraries"

/* Built in default value for GNUstep network library */
#define GNUSTEP_TARGET_NETWORK_LIBRARY "/usr/GNUstep/Local/Library"

/* Built in default value for GNUstep network tools */
#define GNUSTEP_TARGET_NETWORK_TOOLS "/usr/GNUstep/Local/Tools"

/* Built in default value for GNUstep Network Users directory */
#define GNUSTEP_TARGET_NETWORK_USERS_DIR ""

/* Built in default value for GNUstep network web apps */
#define GNUSTEP_TARGET_NETWORK_WEB_APPS "/usr/GNUstep/Local/Library/WebApplications"

/* Built in default value for GNUstep system apps */
#define GNUSTEP_TARGET_SYSTEM_ADMIN_APPS "/usr/GNUstep/System/Applications/Admin"

/* Built in default value for GNUstep system tools */
#define GNUSTEP_TARGET_SYSTEM_ADMIN_TOOLS "/usr/GNUstep/System/Tools/Admin"

/* Built in default value for GNUstep system apps */
#define GNUSTEP_TARGET_SYSTEM_APPS "/usr/GNUstep/System/Applications"

/* Built in default value for GNUstep system documentation */
#define GNUSTEP_TARGET_SYSTEM_DOC "/usr/GNUstep/System/Library/Documentation"

/* Built in default value for GNUstep system info documentation */
#define GNUSTEP_TARGET_SYSTEM_DOC_INFO "/usr/GNUstep/System/Library/Documentation/info"

/* Built in default value for GNUstep system manpages documentation */
#define GNUSTEP_TARGET_SYSTEM_DOC_MAN "/usr/GNUstep/System/Library/Documentation/man"

/* Built in default value for GNUstep system headers */
#define GNUSTEP_TARGET_SYSTEM_HEADERS "/usr/GNUstep/System/Library/Headers"

/* Built in default value for GNUstep system libraries */
#define GNUSTEP_TARGET_SYSTEM_LIBRARIES "/usr/GNUstep/System/Library/Libraries"

/* Built in default value for GNUstep system library */
#define GNUSTEP_TARGET_SYSTEM_LIBRARY "/usr/GNUstep/System/Library"

/* Built in default value for GNUstep system tools */
#define GNUSTEP_TARGET_SYSTEM_TOOLS "/usr/GNUstep/System/Tools"

/* Built in default value for GNUstep System Users directory */
#define GNUSTEP_TARGET_SYSTEM_USERS_DIR ""

/* Built in default value for GNUstep web apps */
#define GNUSTEP_TARGET_SYSTEM_WEB_APPS "/usr/GNUstep/System/Library/WebApplications"

/* Built in default value for GNUstep user config file */
#define GNUSTEP_TARGET_USER_CONFIG_FILE ".GNUstep.conf"

/* Built in default value for GNUstep user defaults directory */
#define GNUSTEP_TARGET_USER_DEFAULTS_DIR "GNUstep/Defaults"

/* Built in default value for GNUstep user_dir admin apps */
#define GNUSTEP_TARGET_USER_DIR_ADMIN_APPS "GNUstep/Applications/Admin"

/* Built in default value for GNUstep user_dir tools */
#define GNUSTEP_TARGET_USER_DIR_ADMIN_TOOLS "GNUstep/Tools/Admin"

/* Built in default value for GNUstep user_dir apps */
#define GNUSTEP_TARGET_USER_DIR_APPS "GNUstep/Applications"

/* Built in default value for GNUstep user_dir documentation */
#define GNUSTEP_TARGET_USER_DIR_DOC "GNUstep/Library/Documentation"

/* Built in default value for GNUstep user_dir info documentation */
#define GNUSTEP_TARGET_USER_DIR_DOC_INFO "GNUstep/Library/Documentation/info"

/* Built in default value for GNUstep user_dir manpages documentation */
#define GNUSTEP_TARGET_USER_DIR_DOC_MAN "GNUstep/Library/Documentation/man"

/* Built in default value for GNUstep user_dir headers */
#define GNUSTEP_TARGET_USER_DIR_HEADERS "GNUstep/Library/Headers"

/* Built in default value for GNUstep user_dir libraries */
#define GNUSTEP_TARGET_USER_DIR_LIBRARIES "GNUstep/Library/Libraries"

/* Built in default value for GNUstep user_dir library */
#define GNUSTEP_TARGET_USER_DIR_LIBRARY "GNUstep/Library"

/* Built in default value for GNUstep user_dir tools */
#define GNUSTEP_TARGET_USER_DIR_TOOLS "GNUstep/Tools"

/* Built in default value for GNUstep user_dir web apps */
#define GNUSTEP_TARGET_USER_DIR_WEB_APPS "GNUstep/Library/WebApplications"

/* Define to 1 if you have the <alloca.h> header file. */
#define HAVE_ALLOCA_H 1

/* Define to 1 if you have the `backtrace' function. */
/* #undef HAVE_BACKTRACE */

/* Define to 1 if you have the <bfd.h> header file. */
/* #undef HAVE_BFD_H */

/* Define to 1 if you have the <callback.h> header file. */
/* #undef HAVE_CALLBACK_H */

/* Define to 1 if you have the `ctime' function. */
#define HAVE_CTIME 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define if you have the dladdr function in the dl library */
#define HAVE_DLADDR 1

/* Define to 1 if you have the <dns_sd.h> header file. */
/* #undef HAVE_DNS_SD_H */

/* Define to 1 if you have the <execinfo.h> header file. */
/* #undef HAVE_EXECINFO_H */

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define if libobjc has the __objc_msg_forward2 function */
#define HAVE_FORWARD2 1

/* Define if GC_allow_register_threads function is available */
/* #undef HAVE_GC_ALLOW_REGISTER_THREADS */

/* Define to 1 if you have the <gc.h> header file. */
/* #undef HAVE_GC_H */

/* Define if GC_register_my_thread function is available */
/* #undef HAVE_GC_REGISTER_MY_THREAD */

/* Define to 1 if you have the `getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the `geteuid' function. */
#define HAVE_GETEUID 1

/* Define to 1 if you have the `getgrgid' function. */
#define HAVE_GETGRGID 1

/* Define to 1 if you have the `getgrgid_r' function. */
#define HAVE_GETGRGID_R 1

/* Define to 1 if you have the `getgrnam' function. */
#define HAVE_GETGRNAM 1

/* Define to 1 if you have the `getgrnam_r' function. */
#define HAVE_GETGRNAM_R 1

/* Define to 1 if you have the `gethostbyaddr_r' function. */
#define HAVE_GETHOSTBYADDR_R 1

/* Define to 1 if you have the `getlogin' function. */
#define HAVE_GETLOGIN 1

/* Define to 1 if you have the `getopt' function. */
#define HAVE_GETOPT 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getpwnam' function. */
#define HAVE_GETPWNAM 1

/* Define to 1 if you have the `getpwnam_r' function. */
#define HAVE_GETPWNAM_R 1

/* Define to 1 if you have the `getpwuid' function. */
#define HAVE_GETPWUID 1

/* Define to 1 if you have the `getpwuid_r' function. */
#define HAVE_GETPWUID_R 1

/* Define if you have this function */
/* #undef HAVE_GICONV */

/* Define to 1 if you have the <gmp.h> header file. */
/* #undef HAVE_GMP_H */

/* Define if libgnutls available */
/* #undef HAVE_GNUTLS */

/* Define to 1 if you have the `gnutls_transport_set_errno' function. */
/* #undef HAVE_GNUTLS_TRANSPORT_SET_ERRNO */

/* Define to 1 if you have the <grp.h> header file. */
#define HAVE_GRP_H 1

/* Define if you have this function */
/* #undef HAVE_ICONV */

/* Define to 1 if you have the `inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define to 1 if you have the `inet_ntop' function. */
#define HAVE_INET_NTOP 1

/* Define to 1 if you have the `inet_pton' function. */
#define HAVE_INET_PTON 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `killpg' function. */
#define HAVE_KILLPG 1

/* Define if you can access the kernel via kvm_open */
/* #undef HAVE_KVM_ENV */

/* Define if you have <langinfo.h> and nl_langinfo(CODESET). */
/* #undef HAVE_LANGINFO_CODESET */

/* Define to 1 if you have the <langinfo.h> header file. */
/* #undef HAVE_LANGINFO_H */

/* Define to 1 if you have the `bfd' library (-lbfd). */
/* #undef HAVE_LIBBFD */

/* Define to 1 if you have the <libc.h> header file. */
/* #undef HAVE_LIBC_H */

/* Define to 1 if you have the `dl' library (-ldl). */
#define HAVE_LIBDL 1

/* Define to 1 if you have the `iberty' library (-liberty). */
/* #undef HAVE_LIBIBERTY */

/* Define to 1 if you have the `kvm' library (-lkvm). */
/* #undef HAVE_LIBKVM */

/* Define to 1 if you have the `m' library (-lm). */
#define HAVE_LIBM 1

/* Define to 1 if you have the `nsl' library (-lnsl). */
#define HAVE_LIBNSL 1

/* Define to 1 if you have the `rt' library (-lrt). */
#define HAVE_LIBRT 1

/* Define if libxml available */
/* #undef HAVE_LIBXML */

/* Define to 1 if you have the <libxml/SAX2.h> header file. */
/* #undef HAVE_LIBXML_SAX2_H */

/* Define if libxslt available */
/* #undef HAVE_LIBXSLT */

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the `link' function. */
#define HAVE_LINK 1

/* Define if your Obj-C compiler calls +load methods before main */
#define HAVE_LOAD_METHOD 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <malloc.h> header file. */
#ifdef __native_client__
#undef HAVE_MALLOC_H
#else
#define HAVE_MALLOC_H 1
#endif

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the `mmap' function. */
/* #undef HAVE_MMAP */

/* Define to 1 if you have the `mprotect' function. */
#define HAVE_MPROTECT 1

/* Define to 1 if you have the `nanosleep' function. */
/* #undef HAVE_NANOSLEEP */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define if objc-api.h defines this function */
#define HAVE_OBJC_GET_UNINSTALLED_DTABLE 1

/* Define to 1 if you have the <objc/objc.h> header file. */
#define HAVE_OBJC_OBJC_H 1

/* Define to 1 if you have the <objc/runtime.h> header file. */
/* #undef HAVE_OBJC_RUNTIME_H */

/* Define to 1 if you have the `objc_setProperty' function. */
/* #undef HAVE_OBJC_SETPROPERTY */

/* Define to 1 if you have the `objc_sync_enter' function. */
/* #undef HAVE_OBJC_SYNC_ENTER */

/* Define to 1 if you have the `objc_thread_add' function. */
#define HAVE_OBJC_THREAD_ADD 1

/* Define to 1 if you have the `poll' function. */
/* #undef HAVE_POLL */

/* Define if poll is NOT emulated via select */
/* #undef HAVE_POLL_F */

/* Define to 1 if you have the <poll.h> header file. */
/* #undef HAVE_POLL_H */

/* Define if system supports the /proc filesystem */
/* #undef HAVE_PROCFS */

/* Define to 1 if you have the <procfs.h> header file. */
/* #undef HAVE_PROCFS_H */

/* Define if system supports reading psinfo from /proc */
/* #undef HAVE_PROCFS_PSINFO */

/* Define if your Lib C defines program_invocation_name */
#define HAVE_PROGRAM_INVOCATION_NAME 1

/* Define to 1 if you have the <pthread.h> header file. */
#define HAVE_PTHREAD_H 1

/* Define this if you work on sysv */
#define HAVE_PTS_STREAM_MODULES 0

/* Define to 1 if you have the <pwd.h> header file. */
/* #undef HAVE_PWD_H */

/* Define to 1 if you have the `readlink' function. */
#define HAVE_READLINK 1

/* Define to 1 if you have the `realpath' function. */
#define HAVE_REALPATH 1

/* Define if you have the register_printf_function function */
/* #undef HAVE_REGISTER_PRINTF_FUNCTION */

/* Define to 1 if you have the `register_printf_specifier' function. */
/* #undef HAVE_REGISTER_PRINTF_SPECIFIER */

/* Define to 1 if you have the `rint' function. */
#define HAVE_RINT 1

/* Define if your system has variable length network addresses */
/* #undef HAVE_SA_LEN */

/* Define to 1 if you have the `setpgid' function. */
#define HAVE_SETPGID 1

/* Define to 1 if you have the `setpgrp' function. */
#define HAVE_SETPGRP 1

/* Define to 1 if you have the `setrlimit' function. */
#define HAVE_SETRLIMIT 1

/* Define to 1 if you have the `setsid' function. */
#define HAVE_SETSID 1

/* Define if libobjc has the objc_set_unexpected() function */
/* #undef HAVE_SET_UNEXPECTED */

/* Define to 1 if you have the `shmctl' function. */
/* #undef HAVE_SHMCTL */

/* Define to 1 if you have the `sigaction' function. */
#define HAVE_SIGACTION 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the `sigsetjmp' function. */
/* #undef HAVE_SIGSETJMP */

/* Define to 1 if the system has the type `socklen_t'. */
#define HAVE_SOCKLEN_T 1

/* Define to 1 if you have the `statvfs' function. */
#define HAVE_STATVFS 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the `strerror_r' function. */
#define HAVE_STRERROR_R 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `symlink' function. */
#define HAVE_SYMLINK 1

/* Define to 1 if you have the `sysctlbyname' function. */
/* #undef HAVE_SYSCTLBYNAME */

/* Define to 1 if you have the `syslog' function. */
/* #undef HAVE_SYSLOG */

/* Define to 1 if you have the <syslog.h> header file. */
/* #undef HAVE_SYSLOG_H */

/* Define to 1 if you have the <sys/cdefs.h> header file. */
#define HAVE_SYS_CDEFS_H 1

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/fcntl.h> header file. */
#define HAVE_SYS_FCNTL_H 1

/* Define to 1 if you have the <sys/file.h> header file. */
#define HAVE_SYS_FILE_H 1

/* Define to 1 if you have the <sys/inttypes.h> header file. */
/* #undef HAVE_SYS_INTTYPES_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
/* #undef HAVE_SYS_IOCTL_H */

/* Define to 1 if you have the <sys/mman.h> header file. */
#define HAVE_SYS_MMAN_H 1

/* Define to 1 if you have the <sys/mount.h> header file. */
#define HAVE_SYS_MOUNT_H 1

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
#define HAVE_SYS_RESOURCE_H 1

/* Define to 1 if you have the <sys/rusage.h> header file. */
/* #undef HAVE_SYS_RUSAGE_H */

/* Define to 1 if you have the <sys/signal.h> header file. */
/* #undef HAVE_SYS_SIGNAL_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/statfs.h> header file. */
/* #undef HAVE_SYS_STATFS_H */

/* Define to 1 if you have the <sys/statvfs.h> header file. */
/* #undef HAVE_SYS_STATVFS_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/stropts.h> header file. */
/* #undef HAVE_SYS_STROPTS_H */

/* Define to 1 if you have the <sys/sysctl.h> header file. */
/* #undef HAVE_SYS_SYSCTL_H */

/* Define to 1 if you have the <sys/syslimits.h> header file. */
/* #undef HAVE_SYS_SYSLIMITS_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
/* #undef HAVE_SYS_UTSNAME_H */

/* Define to 1 if you have the <sys/vfs.h> header file. */
#define HAVE_SYS_VFS_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the `time' function. */
#define HAVE_TIME 1

/* Define to 1 if you have the `times' function. */
#define HAVE_TIMES 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <tzfile.h> header file. */
/* #undef HAVE_TZFILE_H */

/* Define if tzfile.h includes the proper definitions */
/* #undef HAVE_TZHEAD */

/* Define to 1 if you have the `tzset' function. */
/* #undef HAVE_TZSET */

/* Define to 1 if you have the <ucbinclude/sys/resource.h> header file. */
/* #undef HAVE_UCBINCLUDE_SYS_RESOURCE_H */

/* Define to 1 if the system has the type `uintmax_t'. */
#define HAVE_UINTMAX_T 1

/* Define if libobjc has the _objc_unexpected_exception callback */
#define HAVE_UNEXPECTED 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `usleep' function. */
#define HAVE_USLEEP 1

/* Define to 1 if you have the <utime.h> header file. */
#define HAVE_UTIME_H 1

/* Define to 1 if you have the `valloc' function. */
#define HAVE_VALLOC 1

/* Define to 1 if you have the `vasprintf' function. */
#define HAVE_VASPRINTF 1

/* Says whether the visibility attribute works */
#define HAVE_VISIBILITY_ATTRIBUTE 1

/* Define to 1 if you have the `vsprintf' function. */
#define HAVE_VSPRINTF 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define if register_printf_function supports wide characters */
#define HAVE_WIDE_PRINTF_FUNCTION 1

/* Define to 1 if you have the <windows.h> header file. */
/* #undef HAVE_WINDOWS_H */

/* Define to 1 if you have the <zlib.h> header file. */
/* #undef HAVE_ZLIB_H */

/* Define if your system needs to have short/int word aligned */
#define NEED_WORD_ALIGNMENT 0

/* Disable GNUSTEP_CONFIG_FILE environment variable */
#define OPTION_NO_ENVIRONMENT 0

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define as the link to exe of process in /proc filesystem. */
#define PROCFS_EXE_LINK "/proc/self/exe"

/* Define to 1 if the `setpgrp' function takes no argument. */
#define SETPGRP_VOID 1

/* The size of a `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of a `float', as computed by sizeof. */
#define SIZEOF_FLOAT 4

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `pthread_cond_t', as computed by sizeof. */
#define SIZEOF_PTHREAD_COND_T 48

/* The size of a `pthread_mutex_t', as computed by sizeof. */
#define SIZEOF_PTHREAD_MUTEX_T 24

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of a `void*', as computed by sizeof. */
#define SIZEOF_VOIDP 4

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define if using the ffcall library for invocations */
/* #undef USE_FFCALL */

/* Define if using the libffi library for invocations */
/* #undef USE_LIBFFI */

/* Define if vasprintf returns the length printed */
#define VASPRINTF_RETURNS_LENGTH 1

/* Define if vsprintf returns the length printed */
#define VSPRINTF_RETURNS_LENGTH 1

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
