// #line 2 "NSPredicateLexer.m"

// #line 4 "NSPredicateLexer.m"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE predicate_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via predicate_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void predicate_restart (FILE *input_file ,yyscan_t yyscanner );
void predicate__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE predicate__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void predicate__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void predicate__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void predicate_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void predicate_pop_buffer_state (yyscan_t yyscanner );

static void predicate_ensure_buffer_stack (yyscan_t yyscanner );
static void predicate__load_buffer_state (yyscan_t yyscanner );
static void predicate__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER predicate__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE predicate__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE predicate__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE predicate__scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *predicate_alloc (yy_size_t ,yyscan_t yyscanner );
void *predicate_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void predicate_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer predicate__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        predicate_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            predicate__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        predicate_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            predicate__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define predicate_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 81
#define YY_END_OF_BUFFER 82
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[194] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   82,   81,
       62,   18,   64,   60,    8,    9,   81,   63,    1,    2,
       53,   51,    7,   52,   10,   54,   57,   57,   81,   23,
       19,   24,   56,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,    3,    4,    5,
       81,    6,   80,   67,   65,   81,   66,   68,   62,   21,
       14,   55,   59,   57,    0,   50,   26,   22,   25,   20,
       27,   28,   61,   61,   61,   61,   61,   61,   61,   61,
       31,   61,   61,   61,   61,   45,   61,   15,   61,   61,
       61,   61,   61,   16,   80,   79,   69,   72,   73,   74,

       75,   76,   77,   79,   78,   79,   59,   58,   37,   13,
       36,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       41,   61,   17,   61,   61,   61,   61,   61,   43,   69,
        0,    0,   61,   61,   61,   61,   61,   61,   48,   34,
       61,   38,   40,   46,   49,   39,   42,   69,    0,   70,
       61,   61,   61,   61,   44,   47,   61,   61,    0,   61,
       61,   61,   61,   61,   61,   61,   71,   61,   29,   61,
       61,   61,   35,   61,   61,   30,   33,   61,   61,   61,
       61,   61,   32,   61,   61,   61,   61,   61,   61,   61,
       11,   12,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,    1,   23,
       24,   25,    1,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       36,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   54,    1,   36,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   36,   64,   65,   66,   67,
       68,   69,   36,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   80,   81,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[82] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    3,    1,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    1,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[206] =
    {   0,
        0,    0,   77,   78,   79,   80,  133,  214,  179,  469,
       89,  152,  469,  469,  469,  469,  160,  469,  469,  469,
      152,  469,  469,  469,  469,  469,  224,   76,  136,   74,
       77,  105,  469,  123,   55,   53,    0,  122,  137,  126,
      140,  141,  136,  127,  143,  137,  142,  469,  469,  469,
       48,  469,    0,  469,  469,  282,  469,  469,  101,  469,
      469,  469,   86,   91,    0,  469,  469,  469,  469,  469,
      469,  469,    0,  143,  212,  213,  143,  217,  211,  207,
        0,  207,  215,  208,  216,  215,  218,    0,  219,  208,
      222,  217,  220,  469,    0,  469,   96,  469,  469,  469,

      469,  469,  469,    0,  469,    0,   98,    0,    0,    0,
        0,  234,  217,  226,  228,  252,  259,  260,  275,  278,
        0,  277,    0,  274,  281,  284,  285,  286,    0,  103,
        0,    0,  279,  289,  306,  276,  309,  281,    0,    0,
      313,    0,    0,    0,    0,    0,  308,  469,    0,  469,
      313,  328,  325,  327,  322,    0,  334,  324,    0,  321,
      330,  331,  327,  330,  330,  345,  469,  343,    0,  336,
      347,  351,    0,  353,  340,    0,    0,  356,  354,  358,
      360,  373,    0,  374,  378,  381,  368,  370,  385,  387,
        0,    0,  469,  446,  451,  453,  458,  463,  123,  122,

      121,  120,  116,  109,  105
    } ;

static yyconst flex_int16_t yy_def[206] =
    {   0,
      193,    1,  194,  194,  194,  194,  195,  195,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  193,  193,  193,
      193,  193,  197,  193,  193,  198,  193,  193,  193,  193,
      193,  193,  193,  193,  199,  193,  193,  193,  193,  193,
      193,  193,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  193,  197,  193,  193,  193,  193,  193,

      193,  193,  193,  200,  193,  201,  193,  199,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  193,
      202,  203,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  193,  204,  193,
      196,  196,  196,  196,  196,  196,  196,  196,  205,  196,
      196,  196,  196,  196,  196,  196,  193,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,    0,  193,  193,  193,  193,  193,  193,  193,

      193,  193,  193,  193,  193
    } ;

static yyconst flex_int16_t yy_nxt[551] =
    {   0,
       10,   11,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   37,   37,   40,   37,   37,   41,   42,   43,
       44,   37,   37,   45,   46,   37,   37,   37,   37,   47,
       37,   48,   10,   49,   34,   35,   36,   37,   38,   39,
       37,   37,   40,   37,   41,   42,   43,   44,   37,   37,
       45,   46,   37,   37,   37,   37,   47,   37,   50,   51,
       52,   54,   54,   57,   57,   76,   55,   55,   58,   58,
       59,   59,   63,   77,   64,   64,   64,   67,   68,   69,

       70,   71,   59,   59,  107,  107,  107,   63,  167,   64,
       64,   64,  159,   76,  130,  130,  107,  107,  107,  150,
       77,  148,  148,  149,  132,  131,  108,   94,   72,   56,
       56,   56,   56,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   66,
       74,   78,   75,   79,   62,   81,   82,   84,   61,   88,
       85,   80,   93,   89,   83,   60,   86,   90,  193,   92,
      109,   87,  114,   91,   10,   10,   10,   74,   78,   75,
      193,   79,   81,  193,   82,   84,   88,  193,   85,   80,

       93,   89,   83,   86,  193,   90,   92,  109,   87,  114,
       91,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       63,  110,   64,   64,   64,  112,  115,  193,  116,  117,
      118,  119,  120,  121,  122,  124,  125,  113,  126,  123,
      127,  111,  128,  129,  134,   10,   10,   10,  133,  110,
      135,  136,   65,  112,  115,  116,  117,  118,  119,  120,
      121,  122,  124,  125,  113,  126,  123,  127,  111,  128,
      129,  134,   10,   10,   10,  137,  133,  135,  136,   65,

       97,   97,  138,  193,  139,  140,  141,  142,   98,   99,
      193,  143,  144,  100,  145,  146,  147,  193,  151,  152,
      193,  101,  137,  154,  102,  156,  103,  104,  105,  138,
      106,  139,  153,  140,  141,  142,   98,   99,  143,  155,
      144,  100,  145,  146,  147,  151,  157,  152,  101,  158,
      154,  102,  156,  103,  104,  105,  160,  106,  161,  162,
      153,  163,  193,  164,  165,  193,  166,  155,  168,  169,
      170,  171,  172,  173,  157,  174,  158,  175,  193,  176,
      177,  178,  179,  160,  180,  181,  161,  162,  182,  163,
      164,  183,  165,  166,  184,  168,  169,  170,  171,  172,

      173,  185,  186,  174,  187,  175,  176,  188,  177,  178,
      179,  180,  189,  181,  190,  191,  182,  192,  193,  183,
      193,  193,  184,  193,  193,  193,  193,  193,  193,  185,
      186,  193,  187,  193,  193,  188,  193,  193,  193,  189,
      193,  190,  193,  191,  193,  192,   53,   53,   53,   53,
       53,   37,   37,   37,   37,   37,   73,   73,   95,   95,
      193,   95,   95,   96,  193,   96,   96,   96,    9,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,

      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193
    } ;

static yyconst flex_int16_t yy_chk[551] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,   35,    3,    4,    5,    6,
       11,   11,   28,   36,   28,   28,   28,   30,   30,   31,

       31,   31,   59,   59,   63,   63,   63,   64,  205,   64,
       64,   64,  204,   35,   97,   97,  107,  107,  107,  203,
       36,  130,  130,  202,  201,  200,  199,   51,   32,    3,
        4,    5,    6,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,   29,
       34,   38,   34,   39,   21,   40,   41,   42,   17,   44,
       43,   39,   47,   45,   41,   12,   43,   45,    9,   46,
       74,   43,   77,   45,    7,    7,    7,   34,   38,   34,
        0,   39,   40,    0,   41,   42,   44,    0,   43,   39,

       47,   45,   41,   43,    0,   45,   46,   74,   43,   77,
       45,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
       27,   75,   27,   27,   27,   76,   78,    0,   79,   80,
       82,   83,   84,   85,   86,   87,   89,   76,   90,   86,
       91,   75,   92,   93,  113,    8,    8,    8,  112,   75,
      114,  115,   27,   76,   78,   79,   80,   82,   83,   84,
       85,   86,   87,   89,   76,   90,   86,   91,   75,   92,
       93,  113,    8,    8,    8,  116,  112,  114,  115,   27,

       56,   56,  117,    0,  118,  119,  120,  122,   56,   56,
        0,  124,  125,   56,  126,  127,  128,    0,  133,  134,
        0,   56,  116,  136,   56,  138,   56,   56,   56,  117,
       56,  118,  135,  119,  120,  122,   56,   56,  124,  137,
      125,   56,  126,  127,  128,  133,  141,  134,   56,  147,
      136,   56,  138,   56,   56,   56,  151,   56,  152,  153,
      135,  154,    0,  155,  157,    0,  158,  137,  160,  161,
      162,  163,  164,  165,  141,  166,  147,  168,    0,  170,
      171,  172,  174,  151,  175,  178,  152,  153,  179,  154,
      155,  180,  157,  158,  181,  160,  161,  162,  163,  164,

      165,  182,  184,  166,  185,  168,  170,  186,  171,  172,
      174,  175,  187,  178,  188,  189,  179,  190,    0,  180,
        0,    0,  181,    0,    0,    0,    0,    0,    0,  182,
      184,    0,  185,    0,    0,  186,    0,    0,    0,  187,
        0,  188,    0,  189,    0,  190,  194,  194,  194,  194,
      194,  195,  195,  195,  195,  195,  196,  196,  197,  197,
        0,  197,  197,  198,    0,  198,  198,  198,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,

      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
// #line 1 "NSPredicateLexer.lm"
// #line 10 "NSPredicateLexer.lm"
    #import <Foundation/NSPredicate.h>
    #import <Foundation/NSCompoundPredicate.h>
    #import <Foundation/NSComparisonPredicate.h>
    #import <Foundation/NSExpression.h>
    #import <Foundation/NSNull.h>
    #import "NSPredicateInternal.h"
    #import "NSExpressionInternal.h"

    #import "NSPredicateParser.tab.h"

    CF_PRIVATE void _predicate_lexer_create(const char *string, yyscan_t *lexer, YY_BUFFER_STATE *state);
    CF_PRIVATE void _predicate_lexer_destroy(yyscan_t lexer, YY_BUFFER_STATE state);

    static int predicate_get_column(yyscan_t scanner);
    static void predicate_set_column(int column_no, yyscan_t scanner);

    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wunreachable-code"
    #pragma clang diagnostic ignored "-Wunused-function"



// #line 647 "NSPredicateLexer.m"

#define INITIAL 0
#define SINGLE_STRING 1
#define DOUBLE_STRING 2
#define ESCAPED_IDENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int predicate_lex_init (yyscan_t* scanner);

int predicate_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int predicate_lex_destroy (yyscan_t yyscanner );

int predicate_get_debug (yyscan_t yyscanner );

void predicate_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE predicate_get_extra (yyscan_t yyscanner );

void predicate_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *predicate_get_in (yyscan_t yyscanner );

void predicate_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *predicate_get_out (yyscan_t yyscanner );

void predicate_set_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t predicate_get_leng (yyscan_t yyscanner );

char *predicate_get_text (yyscan_t yyscanner );

int predicate_get_lineno (yyscan_t yyscanner );

void predicate_set_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * predicate_get_lval (yyscan_t yyscanner );

void predicate_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int predicate_wrap (yyscan_t yyscanner );
#else
extern int predicate_wrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int predicate_lex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int predicate_lex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

// #line 35 "NSPredicateLexer.lm"


// #line 886 "NSPredicateLexer.m"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			predicate_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				predicate__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		predicate__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 194 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 469 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
// #line 37 "NSPredicateLexer.lm"
{ return LPAREN; }
	YY_BREAK
case 2:
YY_RULE_SETUP
// #line 38 "NSPredicateLexer.lm"
{ return RPAREN; }
	YY_BREAK
case 3:
YY_RULE_SETUP
// #line 39 "NSPredicateLexer.lm"
{ return LSQUARE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
// #line 40 "NSPredicateLexer.lm"
{ return RSQUARE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
// #line 41 "NSPredicateLexer.lm"
{ return LCURLY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
// #line 42 "NSPredicateLexer.lm"
{ return RCURLY; }
	YY_BREAK
case 7:
YY_RULE_SETUP
// #line 44 "NSPredicateLexer.lm"
{ return COMMA; }
	YY_BREAK
case 8:
YY_RULE_SETUP
// #line 45 "NSPredicateLexer.lm"
{ return DOLLAR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
// #line 46 "NSPredicateLexer.lm"
{ return PERCENT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
// #line 47 "NSPredicateLexer.lm"
{ return PERIOD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
// #line 49 "NSPredicateLexer.lm"
{ return TRUE_PREDICATE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
// #line 50 "NSPredicateLexer.lm"
{ return FALSE_PREDICATE; }
	YY_BREAK
case 13:
// #line 53 "NSPredicateLexer.lm"
case 14:
YY_RULE_SETUP
// #line 53 "NSPredicateLexer.lm"
{ return AND; }
	YY_BREAK
case 15:
// #line 55 "NSPredicateLexer.lm"
case 16:
YY_RULE_SETUP
// #line 55 "NSPredicateLexer.lm"
{ return OR; }
	YY_BREAK
case 17:
// #line 57 "NSPredicateLexer.lm"
case 18:
YY_RULE_SETUP
// #line 57 "NSPredicateLexer.lm"
{ return NOT; }
	YY_BREAK
case 19:
// #line 60 "NSPredicateLexer.lm"
case 20:
YY_RULE_SETUP
// #line 60 "NSPredicateLexer.lm"
{ return EQUAL; }
	YY_BREAK
case 21:
// #line 62 "NSPredicateLexer.lm"
case 22:
YY_RULE_SETUP
// #line 62 "NSPredicateLexer.lm"
{ return NOT_EQUAL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
// #line 63 "NSPredicateLexer.lm"
{ return LESS_THAN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
// #line 64 "NSPredicateLexer.lm"
{ return GREATER_THAN; }
	YY_BREAK
case 25:
// #line 66 "NSPredicateLexer.lm"
case 26:
YY_RULE_SETUP
// #line 66 "NSPredicateLexer.lm"
{ return LESS_THAN_OR_EQUAL; }
	YY_BREAK
case 27:
// #line 68 "NSPredicateLexer.lm"
case 28:
YY_RULE_SETUP
// #line 68 "NSPredicateLexer.lm"
{ return GREATER_THAN_OR_EQUAL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
// #line 70 "NSPredicateLexer.lm"
{ return BETWEEN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
// #line 72 "NSPredicateLexer.lm"
{ return CONTAINS; }
	YY_BREAK
case 31:
YY_RULE_SETUP
// #line 73 "NSPredicateLexer.lm"
{ return IN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
// #line 75 "NSPredicateLexer.lm"
{ return BEGINS_WITH; }
	YY_BREAK
case 33:
YY_RULE_SETUP
// #line 76 "NSPredicateLexer.lm"
{ return ENDS_WITH; }
	YY_BREAK
case 34:
YY_RULE_SETUP
// #line 77 "NSPredicateLexer.lm"
{ return LIKE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
// #line 78 "NSPredicateLexer.lm"
{ return MATCHES; }
	YY_BREAK
case 36:
YY_RULE_SETUP
// #line 80 "NSPredicateLexer.lm"
{ return ANY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
// #line 81 "NSPredicateLexer.lm"
{ return ALL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
// #line 82 "NSPredicateLexer.lm"
{ return NONE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
// #line 83 "NSPredicateLexer.lm"
{ return SOME; }
	YY_BREAK
case 40:
// #line 86 "NSPredicateLexer.lm"
case 41:
YY_RULE_SETUP
// #line 86 "NSPredicateLexer.lm"
{ return NULL_TOK; }
	YY_BREAK
case 42:
// #line 88 "NSPredicateLexer.lm"
case 43:
YY_RULE_SETUP
// #line 88 "NSPredicateLexer.lm"
{ return TRUE_TOK; }
	YY_BREAK
case 44:
// #line 90 "NSPredicateLexer.lm"
case 45:
YY_RULE_SETUP
// #line 90 "NSPredicateLexer.lm"
{ return FALSE_TOK; }
	YY_BREAK
case 46:
YY_RULE_SETUP
// #line 91 "NSPredicateLexer.lm"
{ return SELF; }
	YY_BREAK
case 47:
YY_RULE_SETUP
// #line 93 "NSPredicateLexer.lm"
{ return FIRST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
// #line 94 "NSPredicateLexer.lm"
{ return LAST; }
	YY_BREAK
case 49:
YY_RULE_SETUP
// #line 95 "NSPredicateLexer.lm"
{ return SIZE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
// #line 97 "NSPredicateLexer.lm"
{ return ASSIGN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
// #line 99 "NSPredicateLexer.lm"
{ return PLUS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
// #line 100 "NSPredicateLexer.lm"
{ return MINUS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
// #line 101 "NSPredicateLexer.lm"
{ return TIMES; }
	YY_BREAK
case 54:
YY_RULE_SETUP
// #line 102 "NSPredicateLexer.lm"
{ return DIVIDE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
// #line 103 "NSPredicateLexer.lm"
{ return POWER; }
	YY_BREAK
case 56:
YY_RULE_SETUP
// #line 105 "NSPredicateLexer.lm"
{ yylval->string = @"@"; return AT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
// #line 107 "NSPredicateLexer.lm"
{ unsigned int n; sscanf(yytext, "%d", &n); yylval->number = [NSNumber numberWithUnsignedInt:n]; return NUMBER; }
	YY_BREAK
case 58:
YY_RULE_SETUP
// #line 108 "NSPredicateLexer.lm"
{ unsigned int n; sscanf(yytext, "%x", &n); yylval->number = [NSNumber numberWithUnsignedInt:n]; return NUMBER; }
	YY_BREAK
case 59:
YY_RULE_SETUP
// #line 109 "NSPredicateLexer.lm"
{ double n; sscanf(yytext, "%lf", &n); yylval->number = [NSNumber numberWithDouble:n]; return NUMBER; }
	YY_BREAK
case 60:
YY_RULE_SETUP
// #line 111 "NSPredicateLexer.lm"
{ BEGIN(ESCAPED_IDENT); }
	YY_BREAK

case 61:
YY_RULE_SETUP
// #line 114 "NSPredicateLexer.lm"
{ yylval->string = [NSString stringWithUTF8String:yytext]; BEGIN(INITIAL); return IDENTIFIER; }
	YY_BREAK

case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
// #line 117 "NSPredicateLexer.lm"
{ }
	YY_BREAK
case 63:
YY_RULE_SETUP
// #line 119 "NSPredicateLexer.lm"
{ yylval->stringLiteral = [NSMutableString string]; BEGIN(SINGLE_STRING); };
	YY_BREAK
case 64:
YY_RULE_SETUP
// #line 120 "NSPredicateLexer.lm"
{ yylval->stringLiteral = [NSMutableString string]; BEGIN(DOUBLE_STRING); };
	YY_BREAK
case 65:
// #line 123 "NSPredicateLexer.lm"
case 66:
YY_RULE_SETUP
// #line 123 "NSPredicateLexer.lm"
{ yylval->string = yylval->stringLiteral; BEGIN(INITIAL); return STRING; }
	YY_BREAK
case 67:
YY_RULE_SETUP
// #line 125 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\""]; }
	YY_BREAK
case 68:
YY_RULE_SETUP
// #line 126 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"'"]; }
	YY_BREAK

case YY_STATE_EOF(SINGLE_STRING):
case YY_STATE_EOF(DOUBLE_STRING):
// #line 129 "NSPredicateLexer.lm"
{ _parsePredicateError("unterminated string literal"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
// #line 131 "NSPredicateLexer.lm"
{ int c; sscanf(yytext + 1, "%o", &c); [yylval->stringLiteral appendFormat:@"%c", c]; }
	YY_BREAK
case 70:
// #line 133 "NSPredicateLexer.lm"
case 71:
YY_RULE_SETUP
// #line 133 "NSPredicateLexer.lm"
{ int c; sscanf(yytext + 2, "%x", &c); [yylval->stringLiteral appendFormat:@"%C", (unichar)c]; }
	YY_BREAK
case 72:
YY_RULE_SETUP
// #line 135 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\a"]; }
	YY_BREAK
case 73:
YY_RULE_SETUP
// #line 136 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\b"]; }
	YY_BREAK
case 74:
YY_RULE_SETUP
// #line 137 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\f"]; }
	YY_BREAK
case 75:
YY_RULE_SETUP
// #line 138 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\n"]; }
	YY_BREAK
case 76:
YY_RULE_SETUP
// #line 139 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\r"]; }
	YY_BREAK
case 77:
YY_RULE_SETUP
// #line 140 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\t"]; }
	YY_BREAK
case 78:
YY_RULE_SETUP
// #line 141 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendString:@"\v"]; }
	YY_BREAK
case 79:
YY_RULE_SETUP
// #line 143 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendFormat:@"%c", yytext[1]]; }
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
// #line 145 "NSPredicateLexer.lm"
{ [yylval->stringLiteral appendFormat:@"%s", yytext]; }
	YY_BREAK

case 81:
YY_RULE_SETUP
// #line 148 "NSPredicateLexer.lm"
ECHO;
	YY_BREAK
// #line 1351 "NSPredicateLexer.m"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ESCAPED_IDENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * predicate_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( predicate_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of predicate_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					predicate_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			predicate_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) predicate_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 194 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 194 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 193);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					predicate_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( predicate_wrap(yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void predicate_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        predicate_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            predicate__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	predicate__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	predicate__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void predicate__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		predicate_pop_buffer_state();
	 *		predicate_push_buffer_state(new_buffer);
     */
	predicate_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	predicate__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (predicate_wrap()) processing, but the only time this flag
	 * is looked at is after predicate_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void predicate__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE predicate__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) predicate_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in predicate__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) predicate_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in predicate__create_buffer()" );

	b->yy_is_our_buffer = 1;

	predicate__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with predicate__create_buffer()
 * @param yyscanner The scanner object.
 */
    void predicate__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		predicate_free((void *) b->yy_ch_buf ,yyscanner );

	predicate_free((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a predicate_restart() or at EOF.
 */
    static void predicate__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	predicate__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then predicate__init_buffer was _probably_
     * called from predicate_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void predicate__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		predicate__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void predicate_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	predicate_ensure_buffer_stack(yyscanner);

	/* This block is copied from predicate__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from predicate__switch_to_buffer. */
	predicate__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void predicate_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	predicate__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		predicate__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void predicate_ensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)predicate_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in predicate_ensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)predicate_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in predicate_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE predicate__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) predicate_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in predicate__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	predicate__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to predicate_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       predicate__scan_bytes() instead.
 */
YY_BUFFER_STATE predicate__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return predicate__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to predicate_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE predicate__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) predicate_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in predicate__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = predicate__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in predicate__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE predicate_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int predicate_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int predicate_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *predicate_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *predicate_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t predicate_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *predicate_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void predicate_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void predicate_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "predicate_set_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void predicate_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "predicate_set_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see predicate__switch_to_buffer
 */
void predicate_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void predicate_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int predicate_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void predicate_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * predicate_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void predicate_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* predicate_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int predicate_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) predicate_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* predicate_lex_init_extra has the same functionality as predicate_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to predicate_alloc in
 * the yyextra field.
 */

int predicate_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    predicate_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) predicate_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    predicate_set_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from predicate_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * predicate_lex_init()
     */
    return 0;
}

/* predicate_lex_destroy is for both reentrant and non-reentrant scanners. */
int predicate_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		predicate__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		predicate_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	predicate_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        predicate_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * predicate_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    predicate_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *predicate_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *predicate_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void predicate_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see predicate_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

// #line 148 "NSPredicateLexer.lm"



#pragma clang diagnostic pop

void _predicate_lexer_create(const char *string, yyscan_t *lexer, YY_BUFFER_STATE *state)
{
    if (predicate_lex_init(lexer))
    {
        [NSException raise:NSInternalInconsistencyException format:@"Unable to create NSPredicate lexer"];
        return;
    }
    *state = predicate__scan_string(string,*lexer);
}

void _predicate_lexer_destroy(yyscan_t lexer, YY_BUFFER_STATE state)
{
    predicate__delete_buffer(state,lexer);
    predicate_lex_destroy(lexer);
}

